image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_IMAGE_VERSION: "vgarcia96/docker:car-template-api-1.2.0"
  MONGO_LOCAL_PORT: 27077
  API_PORT: 4000

docker-compose-build:
  stage: build
  tags:
    - build
  script:
    - docker build -t $DOCKER_IMAGE_VERSION .

docker-push:
  stage: build
  tags: 
    - build
  script:
    - docker login
    - docker push $DOCKER_IMAGE_VERSION