version: '3'
services:
  car_api:
<<<<<<< HEAD
    image: vgarcia96/docker:car-template-api-1.1.0
=======
    image: ${DOCKER_IMAGE_VERSION}
>>>>>>> feature/parking-microservice
    build:
      context: .
      dockerfile: Dockerfile
    expose: 
      - "80"
    ports:
      - "${API_PORT}:80"
    env_file:
      - api.env
    depends_on:
<<<<<<< HEAD
      - mongo
  car_mongo:
    image: mongo:4.2
    ports:
      - "{DB_LOCAL_PORT}:27017"
=======
      - car_mongo
  car_mongo:
    image: mongo:4.2
    ports:
      - "${DB_LOCAL_PORT}:27017"
>>>>>>> feature/parking-microservice
    volumes:
      - ./db:/data/db
